### ISSUE TITLE
Runtime exception from flutter v 1.5

### ISSUE THREAD

**Issue by harshapulikollu** [aloisdeniel/flutter_geocoder#18]
Encountering a fatal runtime exception after upgrading flutter to version 1.5, resulting in crash of app. 
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(11970): 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
E/AndroidRuntime(11970): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(11970): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(11970): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(11970): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime(11970): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime(11970): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime(11970): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(11970): Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #2
E/AndroidRuntime(11970): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime(11970): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/AndroidRuntime(11970): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:129)
E/AndroidRuntime(11970): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:215)
E/AndroidRuntime(11970): 	at com.aloisdeniel.geocoder.GeocoderPlugin$2.doInBackground(GeocoderPlugin.java:113)
E/AndroidRuntime(11970): 	at com.aloisdeniel.geocoder.GeocoderPlugin$2.doInBackground(GeocoderPlugin.java:106)
E/AndroidRuntime(11970): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(11970): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(11970): 	... 4 more
```

**Comment by lucaslcode** [comment]
See https://github.com/jason-simmons/flutter_plugins/commit/70b9bfc3cb46e459adaec5c13b3da1080ad4aeba on how to fix this

Basically you now have to do `runOnUiThread(Runnable { result.success(myResult) })`

**Comment by harshapulikollu** [comment]
Will look into it. Thankyou.

**Comment by lucaslcode** [comment]
(It might be something the plugin maintainer has to do. Or you could open a pull request fixing it.)

**Comment by lastant** [comment]
Found this issue when working on a completely different Flutter project. In case somebody else needs a fix: for me it was enough to modify my AsyncTask slightly by moving the code that was causing the exception to the onPostExecute method:
```Java
@Override
protected void onPostExecute(HashMap result) {
  //code that was causing the exception, in my case: 
  channel.invokeMethod(...);
}
```

**Comment by pratik037** [comment]
Still facing the issue. Here's the [issue]
(https://github.com/fluttercommunity/flutter_google_places/issues/69#issue-456770398)
*flutter version 1.6.3*
Using Geocode plugin based on a stackOverflow answer.
