### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by fabirt** [aloisdeniel/flutter_geocoder#61]
Please consider migrating to null-safety.

**Comment by filly82** [comment]
yes please

**Comment by higorlapacw** [comment]
Any news, guys?

**Comment by JaffaKetchup** [comment]
Same here!

**Comment by JCKodel** [comment]
I've forked and migrated the project for null safety (had to remove example folder because it was too old).

```
  geocoder:
    git:
      url: https://github.com/JCKodel/flutter_geocoder.git
```

**Comment by higorlapacw** [comment]
@JCKodel I don't think this project is being maintained, so the owner won't accept any PRs. Maybe you should contact him with e-mail or consider uploading you version in pub.dev
What do you think?

**Comment by JCKodel** [comment]
> @JCKodel I don't think this project is being maintained, so the owner won't accept any PRs. Maybe you should contact him with e-mail or consider uploading you version in pub.dev
> What do you think?

Done.
https://pub.dev/packages/flutter_geocoder

**Comment by n0tc0ding** [comment]
Thanks @JCKodel for the package. If someone needs the package for iOS I modified the original version and added some of the changes made from JCK.

This in your pubspec.yaml

>   geocoder:
          git:
              url: git://github.com/n0tc0ding/flutter_geocoder.git

this in your dart code

`import 'package:geocoder/geocoder.dart';`

**Comment by JCKodel** [comment]
> Thanks @JCKodel for the package. If someone needs the package for iOS I modified the original version and added some of the changes made from JCK.
> 
> This in your pubspec.yaml
> 
> > geocoder:
> > git:
> > url: git://github.com/n0tc0ding/flutter_geocoder.git
> 
> this in your dart code
> 
> `import 'package:geocoder/geocoder.dart';`

@n0tc0ding 

Since I've published the package named flutter_geocoder, can you please make a PR for this repository, so I can update the published package (I don't know if it is possible to transfer the ownership of packages, didn't found anything on pub.dev).

**Comment by n0tc0ding** [comment]
@JCKodel Let me read how to that and I will try to do the PR. 

PD: I have never done a PR lol

**Comment by JCKodel** [comment]
> @JCKodel Let me read how to that and I will try to do the PR.
> 
> PD: I have never done a PR lol

The problem is that you forked the original repo, not this one. 
If you fork this repo and then apply your changes, then, it will be easy to create a PR.

**Comment by deakjahn** [comment]
@JCKodel I can't really see which one will be going further :-) but if the other one, please, remove the 'nullsafety' from the version so that it will be a stable package rather than a prerelease one. You could also consider bumping up the version to make it a breaking change.

**Comment by Holofox** [comment]
Use [geocoding](https://pub.dev/packages/geocoding/example) package, migration is simple enough.

**Comment by gushendra86** [comment]
Hello @JCKodel, thank you for migrate it to null safety and it works on Android :) I want to ask a question, when will it be implemented on iOS Device ?

Kind regards

**Comment by JCKodel** [comment]
> Hello @JCKodel, thank you for migrate it to null safety and it works on Android :) I want to ask a question, when will it be implemented on iOS Device ?
> 
> Kind regards

Null safety is Dart only. If this plugin had iOS support, it will keep working. Nothing changes in Java/Objective-C code.

**Comment by gushendra86** [comment]
> 
> 
> > Hello @JCKodel, thank you for migrate it to null safety and it works on Android :) I want to ask a question, when will it be implemented on iOS Device ?
> > Kind regards
> 
> Null safety is Dart only. If this plugin had iOS support, it will keep working. Nothing changes in Java/Objective-C code.

Hello, thanks for your reply. 
But i get this error when running it on iOS :
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method findAddressesFromCoordinates on channel github.com/aloisdeniel/geocoder)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      LocalGeocoding.findAddressesFromCoordinates (package:flutter_geocoder/services/local.dart:13:26)
<asynchronous suspension>
#2      _GoogleMaps15PageState._getAddress (package:maps_flutter/maps/google_maps_flutter/google_maps15.dart:45:21)
<asynchronous suspension>

This is the screenshot
![newww](https://user-images.githubusercontent.com/62778692/114055031-953bdf00-98ba-11eb-8693-d3041e04233a.jpg)

![Screenshot 2021-04-08 222644](https://user-images.githubusercontent.com/62778692/114053969-a0423f80-98b9-11eb-9fe2-1239e106369a.jpg)

When i use from original source (geocoder: ^0.2.1), iOS is not error and can return address.

Thank you and kind regards

**Comment by gushendra86** [comment]
@JCKodel, i found the different is in this path :  flutter_geocoder/ios/Runner/GeneratedPluginRegistrant.m 

Must be edited looks like in this path : https://github.com/n0tc0ding/flutter_geocoder/blob/master/ios/Runner/GeneratedPluginRegistrant.m

This file is different too :
https://github.com/n0tc0ding/flutter_geocoder/blob/master/pubspec.yaml

n0tc0ding :
flutter:
  plugin:
    androidPackage: com.aloisdeniel.geocoder
    pluginClass: GeocoderPlugin
    
JCKodel :
flutter:
  plugin:
    platforms:
      android:
        package: com.aloisdeniel.geocoder
        pluginClass: GeocoderPlugin

Thanks and regards
